version: "3"

networks:
  finance_network:
    driver: bridge

services:
  canal:
    build:
      context: ./canal
    networks:
      - finance_network

  zookeeper:
    build:
      context: ./zookeeper
    ports:
      - "2181:2181"
    networks:
      - finance_network

  kafka:
    build:
      context: ./kafka
    environment:
      - ZOOKEEPER_HOST=zookeeper
      - ZOOKEEPER_PORT=2181
      - TZ=Asia/Shanghai
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - finance_network